-- MySQL Script generated by MySQL Workbench
-- Sun Oct 27 10:39:39 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dbPakmail
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbPakmail
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbPakmail` DEFAULT CHARACTER SET utf8 ;
USE `dbPakmail` ;

-- -----------------------------------------------------
-- Table `dbPakmail`.`franquicia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbPakmail`.`franquicia` ;

CREATE TABLE IF NOT EXISTS `dbPakmail`.`franquicia` (
  `id_franquicia` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_franquicia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbPakmail`.`lt`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbPakmail`.`lt` ;

CREATE TABLE IF NOT EXISTS `dbPakmail`.`lt` (
  `id_lt` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_lt`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbPakmail`.`costo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbPakmail`.`costo` ;

CREATE TABLE IF NOT EXISTS `dbPakmail`.`costo` (
  `id_costo` INT NOT NULL AUTO_INCREMENT,
  `id_frabquicia` INT NOT NULL,
  `id_lt` INT NOT NULL,
  `costo` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id_costo`),
  INDEX `fk_costo_frabquicia_idx` (`id_frabquicia` ASC) ,
  INDEX `fk_costo_lt1_idx` (`id_lt` ASC) ,
  CONSTRAINT `fk_costo_frabquicia`
    FOREIGN KEY (`id_frabquicia`)
    REFERENCES `dbPakmail`.`franquicia` (`id_franquicia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_costo_lt1`
    FOREIGN KEY (`id_lt`)
    REFERENCES `dbPakmail`.`lt` (`id_lt`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbPakmail`.`presupuesto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbPakmail`.`presupuesto` ;

CREATE TABLE IF NOT EXISTS `dbPakmail`.`presupuesto` (
  `id_presupuesto` INT NOT NULL AUTO_INCREMENT,
  `id_franquicia` INT NOT NULL,
  `presupuesto` DECIMAL(10,2) NULL,
  PRIMARY KEY (`id_presupuesto`),
  INDEX `fk_presupuesto_frabquicia1_idx` (`id_franquicia` ASC) ,
  CONSTRAINT `fk_presupuesto_frabquicia1`
    FOREIGN KEY (`id_franquicia`)
    REFERENCES `dbPakmail`.`franquicia` (`id_franquicia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbPakmail`.`venta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbPakmail`.`venta` ;

CREATE TABLE IF NOT EXISTS `dbPakmail`.`venta` (
  `id_venta` INT NOT NULL AUTO_INCREMENT,
  `id_franquicia` INT NOT NULL,
  `venta` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id_venta`),
  INDEX `fk_venta_frabquicia1_idx` (`id_franquicia` ASC) ,
  CONSTRAINT `fk_venta_frabquicia1`
    FOREIGN KEY (`id_franquicia`)
    REFERENCES `dbPakmail`.`franquicia` (`id_franquicia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbPakmail`.`record_deposito`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbPakmail`.`record_deposito` ;

CREATE TABLE IF NOT EXISTS `dbPakmail`.`record_deposito` (
  `id_record_deposito` INT NOT NULL AUTO_INCREMENT,
  `id_franquicia` INT NOT NULL,
  `record_deposito` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id_record_deposito`),
  INDEX `fk_record_deposito_frabquicia1_idx` (`id_franquicia` ASC) ,
  CONSTRAINT `fk_record_deposito_frabquicia1`
    FOREIGN KEY (`id_franquicia`)
    REFERENCES `dbPakmail`.`franquicia` (`id_franquicia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbPakmail`.`recor_facturacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbPakmail`.`recor_facturacion` ;

CREATE TABLE IF NOT EXISTS `dbPakmail`.`recor_facturacion` (
  `id_recor_facturacion` INT NOT NULL AUTO_INCREMENT,
  `id_franquicia` INT NOT NULL,
  `recor_facturacion` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id_recor_facturacion`),
  INDEX `fk_recor_facturacion_frabquicia1_idx` (`id_franquicia` ASC) ,
  CONSTRAINT `fk_recor_facturacion_frabquicia1`
    FOREIGN KEY (`id_franquicia`)
    REFERENCES `dbPakmail`.`franquicia` (`id_franquicia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
